### ISSUE TITLE
O script indexa apenas 2300 e poucos linls.

### ISSUE THREAD

**Issue by fang0rnz** [fang0rnz/lelivroscraper#2]
Por algum motivo, o script ta indexando apenas 2300 e poucos livros dos mais de 6000 do lelivros. Talvez um problema de overflow no set?

**Comment by carlosasj** [comment]
O problema acontece a partir da página 150/151 ("estatística" em 26/09/2016).
Isso ocorre porque o `signal` que ele procura é `em-pdf-epub-e-mobi-ou-ler-online/`, já que os links das primeiras páginas segue o padrão:
`http://lelivros.me/book/baixar-livro-{{nome_do_livro}}-em-pdf-epub-e-mobi-ou-ler-online/`

A partir da página 150/151 os links seguem o padrão:
`http://lelivros.me/book/baixar-livro-{{nome_do_livro}}-em-pdf-epub-e-mobi/`

Sugestão: trocar o valor de `signal` para `em-pdf-epub-e-mobi` sem a barra no final, para abranger os dois casos.
